# Custom Travis.yml File

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules

# Prepare our tests
# Ensure the project is setup correctly and compiled
before_script: "npm run compile"

# Run our tests
script: "npm start"
