# Custom Travis.yml File

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules

# Prepare our tests
# Ensure the project is setup correctly and compiled
before_script: "npm run compile"

# Run our tests
script: "npm start"

# Custom notifications
notifications:
  email:
    recipients:
      secure: Z8X/0WI+IOtLC0w7kuSkC4ZZvCrOHfyN8I3lJ9FI/ybpfVxjQYPvdbwyMNGLHIabcB0x1DzzFCeovX15iS6xpNmN7lffAFsgNI00WviLboXj4UOQ+P5FZUVDkqjNE526X85X+v+VuAkOTO7bphLgVqrPo/5jlkb1Jxop2vBRl50=
  slack:
    secure: VNXUY9+dKrkgp98PmD9FGyuHScgmtQhlOijb4Pli0WAMbx4be+lgDAkb20MkJ96U3JTemU2XuzTdB+Q/azXucNv8H6SPysQqsx0Qt++cIGjVzAVKVQtNN+wNjf7fPHQ1pJQHLyzdN6zdHOI+P9M/QKVjUmjAWp2u3IjvpDFsyt4=
